### ISSUE TITLE
"Timeout error"

### ISSUE THREAD

**Issue by chewie-21** [PrimeSense/Sensor#3]
Hello, I'm writing you this e-mail because I've an important problem with the kinect, when I launch my program which uses the kinect (a visual studio solution compilated executable), I have the error "A timeout has occured when waiting for data".

I have the following software components and drivers :
- the kinect driver "avin2-SensorKinect-28738dc" 
- the version 1.1.0.41 of OpenNI  
- the version 1.3.1.5 of Nite Bin

I tried different versions of everything (drivers, openNI and nite) but the error is stil there.

If you have any idea or if you can help me to solve this problem, I thank you very much and I'm wainting for your response.

cordially,

Vince

**Comment by PrimeSense** [comment]
What happens when you use the NiViewer sample? Does it work?

Ziv.

-----Original Message-----
From: everdyn [mailto:reply@reply.github.com] 
Sent: Wednesday, May 11, 2011 11:02 AM
To: Ziv Hendel
Subject: [Sensor] "Timeout error" (#3)

Hello, I'm writing you this e-mail because I've an important problem with the kinect, when I launch my program which uses the kinect (a visual studio solution compilated executable), I have the error "A timeout has occured when waiting for data".

I have the following software components and drivers :
- the kinect driver "avin2-SensorKinect-28738dc" 
- the version 1.1.0.41 of OpenNI  
- the version 1.3.1.5 of Nite Bin

I tried different versions of everything (drivers, openNI and nite) but the error is stil there.

If you have any idea or if you can help me to solve this problem, I thank you very much and I'm wainting for your response.

cordially,

Vince

## 

Reply to this email directly or view it on GitHub:
https://github.com/PrimeSense/Sensor/issues/3

**Comment by chewie-21** [comment]
Yes the NiViewer sample works well and I have the depth image and the simple camera image.

Vince

**Comment by PrimeSense** [comment]
How do you init the sensor?
From API calls or via XML?

-----Original Message-----

**Comment by chewie-21** [comment]
I init the sensor via XML

**Comment by PrimeSense** [comment]
Can you use the same XML that NiViewer is using?
("c:\Program Files\OpenNI\Data\SamplesConfig.xml")

I guess that there's a problem in your XML file...

Ziv.

-----Original Message-----

**Comment by twocs** [comment]
This page is for bug reports, but the issue seems to be in your code, not in PrimeSense/Sensor. Therefore, it looks like the mailing list would be a good place to address this issue. 

Forum: http://groups.google.com/group/openni-dev

By the way it is an interesting issue for a common problem, so I hope it can be addressed on the Wiki also. It is probably related to the resolution of the cameras, which is different for Kinect, and means change that can occur in the xml file. However I thought that all xml resolution problem was solved in the new versions of avin2/SensorKinect. The problem I had with avin2/SensorKinect was solved when I changed to the OpenNI unstable branch.
